NUMPY

In [ ]:
#importing the library
import numpy as np

In [ ]:
# create a empty array

# var = np.array([])

arr = np.array([])

print(arr)

[]


In [ ]:
type(arr)  #nd --> n dimensional array

numpy.ndarray

In [ ]:
#create a array which holds , 2,3,4,5,5,2,1

arr1 = np.array([2,3,4,5,5,2,1])
print(arr1)

[2 3 4 5 5 2 1]


In [ ]:
# 10,20,30,50
#type

arr2 = np.array([10,20,30,40])
arr2

array([10, 20, 30, 40])

In [ ]:
#string values

arr3 = np.array(('a','b','c'))
print(arr3)

['a' 'b' 'c']


In [ ]:
#create a array suing a list

list = [1,2,3,4,5]

array_list = np.array(list)
print(array_list)

[1 2 3 4 5]


In [ ]:
#create a array using tuple

tuple = (1,2,3,4,4,5,6)

array_tuple = np.array(tuple)
print(array_tuple)

[1 2 3 4 4 5 6]


1 D ----> 1 dimension

In [ ]:
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [ ]:
print('Dimension ',array.ndim)

print('Number of elements ',array.size)

print('The datatype of the array ',array.dtype)

Dimension  1
Number of elements  5
The datatype of the array  int64


In [ ]:
#array of float datatype and perform the previous steps

2 D - ARRAY


These are called matrices (matrix) --> rectangular arrangement of elements in the form of rows and columns

In [ ]:
#2d

#array_2d = np.array( [ [],[],[] ] )

array_2d = np.array([[1,2],[3,4]])
print(array_2d)

[[1 2]
 [3 4]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a)

print(a.ndim)
print(a.dtype)
print(a.size)
print('order of the matrix',a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
int64
9
order of the matrix (3, 3)


3D --> 3 dimension

In [ ]:
b = np.array( [ [ [1,2],[3,4],[2,4] ] ] )
print(b)

[[[1 2]
  [3 4]
  [2 4]]]


In [ ]:
print(b.ndim)
print(b.dtype)
print(b.size)
print('order of the matrix',b.shape)

3
int64
6
order of the matrix (1, 3, 2)


BUILT IN function to generate numpy array

In [ ]:
#arange ---> it is used to generate evenly space values within a given interval

# 0 to 10   1,2,3,4,5,6,,,,10

#100
#it'll not include the end value in the given range

np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#30

np.arange(31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# 1 to 10

#start 1 end 11

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#101 to 500


In [ ]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#10 multiples of 5

np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

ONES

returns an array with all one's

In [ ]:
#1-d array with 10elments hving value 1
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#2d

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
#(5,3)
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Zeros

return an array with all zero as its value

In [ ]:
np.zeros(5)  #1d

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2)) #2d

array([[0., 0.],
       [0., 0.]])

indentity

all the diagonal values will be 1, rest all the values will be 0

In [ ]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#full  -----. used to generate array with same elemnts

#np.full((dimension),value)

np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [ ]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
import numpy as np

In [ ]:
#linspace ---> linear space

# using linspace we cam genearte linearly spaced values

np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
np.linspace(1,100,retstep = True)

(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
         65.65306122,  67.67346939,  69.69387755,  71.71428571,
         73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
         81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]),
 2.020408163265306)

In [ ]:
np.linspace(1,1000,num = 10,retstep = True)

(array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.]),
 111.0)

Random generation of numbers

In [ ]:
#randint  -> it is used to generate random integers from the interval

#create an array which includes 10 random intergers 1 to 100

np.random.randint(1,100,10)   #(start, end , number of random integers you want)

array([71, 82,  6, 91, 15, 99, 10, 17, 53, 77])

In [ ]:
#5 random intergers 1 to 1000

np.random.randint(1,1000,5)

array([326, 272, 655,  39, 734])

In [ ]:
#2d array

np.random.randint (10,30,size=(2,2))

array([[13, 20],
       [10, 24]])

In [ ]:
np.random.randint (10,30,size=(3,3))

array([[22, 22, 22],
       [24, 13, 29],
       [14, 24, 15]])

In [ ]:
#2d array order(2,3) range 2 to 200
np.random.randint(2,200,size=(2,3))

array([[183, 114,  23],
       [ 36, 176, 107]])

In [ ]:
# rand --- it generates random values betwen the range of [0,1]

#10 random intergers between 0 to 1

np.random.rand(10)

array([0.05659468, 0.73894045, 0.21353982, 0.35015614, 0.79870464,
       0.11716821, 0.80872359, 0.7557124 , 0.82426959, 0.08880121])

In [ ]:
np.random.rand(50)

array([0.41513695, 0.9998607 , 0.78197056, 0.94724866, 0.57403965,
       0.71671821, 0.24919475, 0.21502727, 0.45713014, 0.82774348,
       0.47117646, 0.3934602 , 0.49801831, 0.98445983, 0.5876238 ,
       0.74380979, 0.11533812, 0.51735509, 0.6734464 , 0.10090491,
       0.30686495, 0.10681721, 0.73646098, 0.97621995, 0.80152739,
       0.15578598, 0.23044689, 0.19237173, 0.15884902, 0.28110883,
       0.52054565, 0.17050513, 0.40271858, 0.76412136, 0.24736029,
       0.75804401, 0.60611242, 0.52595952, 0.3576    , 0.57719177,
       0.90683225, 0.49040649, 0.22074037, 0.3515202 , 0.36003175,
       0.55540962, 0.25315099, 0.5615607 , 0.68437573, 0.3112982 ])

In [ ]:
#create a 2d array (4,4) with random numbers between 0 to 1

np.random.rand(4,4)

array([[0.86421561, 0.97187864, 0.43525333, 0.82623505],
       [0.38217066, 0.82100361, 0.19987811, 0.01505084],
       [0.68962783, 0.0320977 , 0.54639156, 0.26309684],
       [0.16790515, 0.91277129, 0.79404907, 0.22078841]])

In [ ]:
#(7,3)
np.random.rand(7,3)

array([[0.85628311, 0.91366276, 0.61214492],
       [0.65756117, 0.16937189, 0.11251364],
       [0.43013901, 0.37715155, 0.47963686],
       [0.66243687, 0.09983769, 0.51573248],
       [0.80562719, 0.44505632, 0.49157297],
       [0.03316971, 0.82418307, 0.40528852],
       [0.15899675, 0.23569926, 0.87807524]])

In [ ]:
#randn --->it is used to generate random numbers from normal distribution within a range [-3 3]



In [ ]:
#generate 10 random numbers from normal distribution

#you are generating 10 random numbers in the range of [-3 3]

np.random.randn(10)

array([ 0.31816509, -0.28031564,  0.50472458, -0.6748867 ,  0.01709673,
        0.6707227 , -0.64195863, -2.01730828, -2.80968349, -0.5188628 ])

In [ ]:
np.random.randn(5,5)

array([[-0.71725114, -1.90611559,  0.76042061,  0.37439826, -1.08888504],
       [ 0.90006492,  1.54307257,  1.67999535,  1.45437395, -1.95133838],
       [ 0.9964016 , -0.59070174, -0.34439068,  1.67444659,  1.68058713],
       [-0.56439722,  0.28275513,  0.75309888,  1.43594237,  0.16242077],
       [ 1.0450776 ,  0.0208264 , -0.25226881,  0.28683491,  0.13817772]])

In [ ]:
#create 10 random intergers 1 , 1000

a = np.random.randint(1,1000,10)
print(a)

[ 54 761  17 309 115 956  24 409 131 230]


In [ ]:
#maximun number

np.max(a)

956

In [ ]:
# argmax - it used to get the index value of the maximun value in the array

np.argmax(a)

5

In [ ]:
#minimun

np.min(a)

17

In [ ]:
np.argmin(a)

2

Indexing

In [ ]:
b = np.arange(10,20)
print(b)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
#fetch 1219

#array_name[ index number]

b[2]

12

In [ ]:
#last

b[-1]

19

In [ ]:
#first

b[0]

10

In [ ]:
print(b)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
b[1:4]

array([11, 12, 13])

In [ ]:
#reverse

b[ : : -1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

Indexing with 2d array

In [ ]:
a = np.array([[1,2,3],[3,4,5],[7,8,9]])
print(a)


[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [ ]:
#fetch first row

print(a[[0]])

[[1 2 3]]


In [ ]:
#fetch first row

print(a[[1]])

[[3 4 5]]


In [ ]:
#fetch first row

print(a[[2]])

[[7 8 9]]


In [ ]:
#fetch first and second row

a[[0,1]]


array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
#fetching 2nd and 3rd row
a[[1,2]]

array([[3, 4, 5],
       [7, 8, 9]])

In [ ]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [ ]:
a[0][0]

1

In [ ]:
a[2][2]

9

In [ ]:
#fetch first column

a[:,[0]]

array([[1],
       [3],
       [7]])

In [ ]:
a[:,[1]]

array([[2],
       [4],
       [8]])

In [ ]:
a[:,[1,2]]

array([[2, 3],
       [4, 5],
       [8, 9]])

In [ ]:
a1 = np.array([10,20,30,40,50])

a2 = np.array([2,4,6,8,10])

In [ ]:
a1 + a2

array([12, 24, 36, 48, 60])

In [ ]:
a1 - a2

array([ 8, 16, 24, 32, 40])

In [ ]:
a1 * a2

array([ 20,  80, 180, 320, 500])

In [ ]:
a1 / a2

array([5., 5., 5., 5., 5.])